/* The public annotation relation, emitted in the caller connection. */
static const char *const duckvep_annotate_parts[] = {
    "WITH parameters AS MATERIALIZED (SELECT CAST(__DUCKVEP_MODEL__ AS VARCHAR) AS model_name, ",
    "coalesce(CAST(__DUCKVEP_HGVS__ AS BOOLEAN), false) AS include_hgvs, ",
    "coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false) AS include_rich, ",
    "CAST(__DUCKVEP_UPSTREAM__ AS UBIGINT) AS upstream_distance, ",
    "CAST(__DUCKVEP_DOWNSTREAM__ AS UBIGINT) AS downstream_distance), ",
    "source AS (SELECT CAST(e.event_index AS UBIGINT) AS __duckvep_event_index, ",
    "CAST(e.seq_region AS UINTEGER) AS __duckvep_seq_region, ",
    "CAST(e.position AS UBIGINT) AS __duckvep_position, ",
    "CAST(e.reference AS VARCHAR) AS __duckvep_reference, ",
    "CAST(e.alternate AS VARCHAR) AS __duckvep_alternate, ",
    "CAST(e.end_position AS UBIGINT) AS __duckvep_end_position, ",
    "upper(CAST(e.structural_type AS VARCHAR)) AS __duckvep_explicit_structural_type, ",
    "upper(CAST(e.copy_change AS VARCHAR)) AS __duckvep_explicit_copy_change, ",
    "CAST(e.mate_seq_region AS UINTEGER) AS __duckvep_mate_seq_region, ",
    "CAST(e.mate_position AS UBIGINT) AS __duckvep_mate_position ",
    "FROM __DUCKVEP_EVENTS__ e), ",
    "typed_base AS MATERIALIZED (SELECT *, ",
    "CASE __duckvep_alternate ",
    "WHEN '<DEL>' THEN 'DEL' WHEN '<DUP>' THEN 'DUP' ",
    "WHEN '<TDUP>' THEN 'TDUP' WHEN '<STR>' THEN 'STR' ",
    "WHEN '<INV>' THEN 'INV' WHEN '<INS>' THEN 'INS' ",
    "WHEN '<CNV>' THEN 'CNV' WHEN '<UNKNOWN>' THEN 'UNKNOWN' ",
    "ELSE NULL END AS __duckvep_symbolic_structural_type, ",
    "__duckvep_alternate = '<*>' AS __duckvep_unspecified_alt, ",
    "__duckvep_alternate IN ('<NON_REF>', '*', '.') ",
    "AS __duckvep_non_variant FROM source), ",
    "typed AS MATERIALIZED (SELECT *, ",
    "coalesce(__duckvep_explicit_structural_type, ",
    "__duckvep_symbolic_structural_type) AS __duckvep_structural_type ",
    "FROM typed_base), ",
    "classified AS MATERIALIZED (SELECT *, CASE ",
    "WHEN __duckvep_non_variant THEN 'non_variant' ",
    "WHEN __duckvep_unspecified_alt THEN 'small_variant' ",
    "WHEN __duckvep_mate_seq_region IS NOT NULL OR __duckvep_mate_position IS NOT NULL ",
    "THEN 'breakend' WHEN __duckvep_explicit_structural_type IS NOT NULL ",
    "OR __duckvep_explicit_copy_change IS NOT NULL ",
    "OR (__duckvep_alternate IS NOT NULL AND ",
    "(starts_with(__duckvep_alternate, '<') OR contains(__duckvep_alternate, '[') ",
    "OR contains(__duckvep_alternate, ']'))) ",
    "OR (__duckvep_end_position IS NOT NULL AND ",
    "(__duckvep_reference IS NULL OR __duckvep_alternate IS NULL)) ",
    "THEN 'structural_variant' ",
    "ELSE 'small_variant' END AS __duckvep_event_kind, ",
    "coalesce(__duckvep_explicit_copy_change, CASE __duckvep_structural_type ",
    "WHEN 'DEL' THEN 'LOSS' WHEN 'DUP' THEN 'GAIN' WHEN 'TDUP' THEN 'GAIN' ",
    "ELSE 'UNKNOWN' END) AS __duckvep_copy_change FROM typed), ",
    "validation AS MATERIALIZED (SELECT CASE ",
    "WHEN (SELECT model_name IS NULL OR model_name = '' FROM parameters) ",
    "THEN error('duckvep_annotate: model_name must be non-empty') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_event_index IS NULL) ",
    "THEN error('duckvep_annotate: event_index is required') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_seq_region IS NULL ",
    "OR __duckvep_position IS NULL OR __duckvep_position = 0) ",
    "THEN error('duckvep_annotate: seq_region and positive one-based position are required') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_event_kind = 'non_variant' ",
    "AND (__duckvep_explicit_structural_type IS NOT NULL ",
    "OR __duckvep_explicit_copy_change IS NOT NULL ",
    "OR __duckvep_mate_seq_region IS NOT NULL ",
    "OR __duckvep_mate_position IS NOT NULL)) ",
    "THEN error('duckvep_annotate: a non-variant gVCF allele cannot carry structural or breakend fields') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_unspecified_alt ",
    "AND (__duckvep_explicit_structural_type IS NOT NULL ",
    "OR __duckvep_explicit_copy_change IS NOT NULL ",
    "OR __duckvep_mate_seq_region IS NOT NULL ",
    "OR __duckvep_mate_position IS NOT NULL)) ",
    "THEN error('duckvep_annotate: <*> cannot carry structural or breakend fields') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE ",
    "(__duckvep_mate_seq_region IS NULL) != (__duckvep_mate_position IS NULL)) ",
    "THEN error('duckvep_annotate: a breakend requires both mate_seq_region and mate_position') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_event_kind = 'breakend' AND ",
    "(__duckvep_end_position IS NOT NULL OR __duckvep_explicit_structural_type IS NOT NULL ",
    "OR __duckvep_explicit_copy_change IS NOT NULL)) ",
    "THEN error('duckvep_annotate: breakend mate coordinates cannot be mixed with single-locus structural fields') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_event_kind = 'breakend' ",
    "AND __duckvep_mate_position = 0) ",
    "THEN error('duckvep_annotate: mate_position must be positive and one-based') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_event_kind = 'small_variant' ",
    "AND (__duckvep_reference IS NULL OR __duckvep_reference = '' ",
    "OR __duckvep_alternate IS NULL OR __duckvep_alternate = '')) ",
    "THEN error('duckvep_annotate: literal small variants require reference and alternate') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE ",
    "__duckvep_explicit_structural_type IS NOT NULL ",
    "AND __duckvep_symbolic_structural_type IS NOT NULL ",
    "AND __duckvep_explicit_structural_type <> __duckvep_symbolic_structural_type) ",
    "THEN error('duckvep_annotate: symbolic alternate and structural_type disagree') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_event_kind = 'structural_variant' ",
    "AND (__duckvep_structural_type IS NULL OR __duckvep_end_position IS NULL)) ",
    "THEN error('duckvep_annotate: a structural event requires end_position and a supported structural_type') ",
    "WHEN EXISTS (SELECT 1 FROM classified WHERE __duckvep_event_kind = 'structural_variant' ",
    "AND __duckvep_structural_type NOT IN ('DEL','DUP','TDUP','STR','INV','INS','CNV','UNKNOWN')) ",
    "THEN error('duckvep_annotate: unsupported structural_type') ",
    "ELSE true END AS valid), ",
    "validated AS (SELECT classified.* FROM classified CROSS JOIN validation ",
    "WHERE validation.valid), ",
    "small_events AS (SELECT * FROM validated ",
    "WHERE __duckvep_event_kind = 'small_variant'), ",
    "structural_events AS (SELECT * FROM validated ",
    "WHERE __duckvep_event_kind = 'structural_variant'), ",
    "breakend_events AS (SELECT * FROM validated ",
    "WHERE __duckvep_event_kind = 'breakend'), ",
    "small_compact_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_small_compact(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_reference, __duckvep_alternate, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM small_events e CROSS JOIN parameters p ",
    "WHERE (NOT p.include_hgvs OR __duckvep_unspecified_alt) ",
    "AND NOT p.include_rich), ",
    "small_hgvs_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_small_hgvs(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_reference, __duckvep_alternate, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM small_events e CROSS JOIN parameters p ",
    "WHERE p.include_hgvs AND NOT __duckvep_unspecified_alt ",
    "AND NOT p.include_rich), ",
    "small_rich_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_small_rich(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_reference, __duckvep_alternate, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM small_events e CROSS JOIN parameters p ",
    "WHERE (NOT p.include_hgvs OR __duckvep_unspecified_alt) ",
    "AND p.include_rich), ",
    "small_rich_hgvs_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_small_rich_hgvs(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_reference, __duckvep_alternate, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM small_events e CROSS JOIN parameters p ",
    "WHERE p.include_hgvs AND NOT __duckvep_unspecified_alt ",
    "AND p.include_rich), ",
    "structural_compact_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_structural_compact(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_end_position, __duckvep_structural_type, ",
    "__duckvep_copy_change, p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM structural_events e CROSS JOIN parameters p WHERE NOT p.include_rich), ",
    "structural_rich_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_structural_rich(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_end_position, __duckvep_structural_type, ",
    "__duckvep_copy_change, p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM structural_events e CROSS JOIN parameters p WHERE p.include_rich), ",
    "breakend_compact_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_breakend_compact(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_mate_seq_region, __duckvep_mate_position, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM breakend_events e CROSS JOIN parameters p WHERE NOT p.include_rich), ",
    "breakend_rich_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_breakend_rich(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_mate_seq_region, __duckvep_mate_position, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM breakend_events e CROSS JOIN parameters p WHERE p.include_rich), ",
    "small_compact AS (SELECT __duckvep_event_index AS event_index, ",
    "__duckvep_event_kind AS duckvep_event_kind, annotation.* ",
    "FROM small_compact_raw), ",
    "small_hgvs AS (SELECT __duckvep_event_index AS event_index, ",
    "__duckvep_event_kind AS duckvep_event_kind, annotation.* FROM small_hgvs_raw), ",
    "small_rich AS (SELECT __duckvep_event_index AS event_index, ",
    "__duckvep_event_kind AS duckvep_event_kind, ",
    "annotation.* EXCLUDE (status, reason), annotation.status AS duckvep_status, ",
    "annotation.reason AS duckvep_reason FROM small_rich_raw), ",
    "small_rich_hgvs AS (SELECT __duckvep_event_index AS event_index, ",
    "__duckvep_event_kind AS duckvep_event_kind, ",
    "annotation.* EXCLUDE (status, reason), annotation.status AS duckvep_status, ",
    "annotation.reason AS duckvep_reason ",
    "FROM small_rich_hgvs_raw), ",
    "structural_compact AS (SELECT __duckvep_event_index AS event_index, ",
    "__duckvep_event_kind AS duckvep_event_kind, annotation.* ",
    "FROM structural_compact_raw), ",
    "structural_rich AS (SELECT __duckvep_event_index AS event_index, ",
    "__duckvep_event_kind AS duckvep_event_kind, ",
    "annotation.* EXCLUDE (status, reason), annotation.status AS duckvep_status, ",
    "annotation.reason AS duckvep_reason ",
    "FROM structural_rich_raw), ",
    "breakend_compact AS (SELECT __duckvep_event_index AS event_index, ",
    "__duckvep_event_kind AS duckvep_event_kind, annotation.* ",
    "FROM breakend_compact_raw), ",
    "breakend_rich AS (SELECT __duckvep_event_index AS event_index, ",
    "__duckvep_event_kind AS duckvep_event_kind, ",
    "annotation.* EXCLUDE (status, reason), annotation.status AS duckvep_status, ",
    "annotation.reason AS duckvep_reason ",
    "FROM breakend_rich_raw) ",
    "SELECT * FROM small_compact UNION ALL BY NAME SELECT * FROM small_hgvs ",
    "UNION ALL BY NAME SELECT * FROM small_rich ",
    "UNION ALL BY NAME SELECT * FROM small_rich_hgvs ",
    "UNION ALL BY NAME SELECT * FROM structural_compact ",
    "UNION ALL BY NAME SELECT * FROM structural_rich ",
    "UNION ALL BY NAME SELECT * FROM breakend_compact ",
    "UNION ALL BY NAME SELECT * FROM breakend_rich",
};
