/* Projection SQL, with the projection expressions inline. */
static const char *const duckvep_projection_parts[] = {
    "WITH events AS MATERIALIZED (\n",
    "  SELECT event_index::UBIGINT AS event_index, seq_region::UINTEGER AS seq_region,\n",
    "    position::UBIGINT AS position, reference::VARCHAR AS reference,\n",
    "    alternate::VARCHAR AS alternate FROM __DUCKVEP_EVENTS_TABLE__\n",
    "), annotations AS MATERIALIZED (\n",
    "  SELECT event_index::UBIGINT AS event_index, transcript_index::UINTEGER AS transcript_index,\n",
    "    consequence_mask::UBIGINT AS consequence_mask FROM __DUCKVEP_ANNOTATIONS_TABLE__\n",
    "), transcripts AS MATERIALIZED (\n",
    "  SELECT transcript_index, seq_region, transcript_start, transcript_end, cds_start, cds_end,\n",
    "    strand, exons, transcript_flags, peptide_edits, cds_sequence, post_cds_sequence, codon_table\n",
    "  FROM __DUCKVEP_TRANSCRIPTS_TABLE__\n",
    "), validation AS MATERIALIZED (\n",
    "  SELECT CASE\n",
    "    WHEN EXISTS (SELECT 1 FROM events WHERE event_index IS NULL OR seq_region IS NULL\n",
    "      OR position IS NULL OR position = 0 OR reference IS NULL OR alternate IS NULL)\n",
    "      THEN error('duckvep_transcript_projection: event keys, position and literal alleles are required')\n",
    "    WHEN EXISTS (SELECT event_index FROM events GROUP BY event_index HAVING count(*) != 1)\n",
    "      THEN error('duckvep_transcript_projection: event_index must be unique')\n",
    "    WHEN EXISTS (SELECT transcript_index FROM transcripts GROUP BY transcript_index\n",
    "      HAVING count(*) != 1 OR transcript_index IS NULL)\n",
    "      THEN error('duckvep_transcript_projection: transcript_index must be non-null and unique')\n",
    "    WHEN EXISTS (SELECT 1 FROM annotations a LEFT JOIN events e USING(event_index)\n",
    "      WHERE e.event_index IS NULL OR a.consequence_mask IS NULL)\n",
    "      THEN error('duckvep_transcript_projection: annotation needs a source event and consequence mask')\n",
    "    WHEN EXISTS (SELECT 1 FROM annotations a JOIN events e USING(event_index)\n",
    "      LEFT JOIN transcripts t USING(transcript_index)\n",
    "      WHERE a.transcript_index IS NOT NULL AND\n",
    "        (t.transcript_index IS NULL OR e.seq_region IS DISTINCT FROM t.seq_region))\n",
    "      THEN error('duckvep_transcript_projection: annotation transcript and source region must match the model')\n",
    "    ELSE true END AS valid\n",
    "), selected_transcripts AS MATERIALIZED (\n",
    "  SELECT t.* EXCLUDE(cds_sequence, post_cds_sequence),\n",
    "    upper(decode(t.cds_sequence)) AS cds_sequence,\n",
    "    upper(decode(t.post_cds_sequence)) AS post_cds_sequence\n",
    "  FROM transcripts t SEMI JOIN annotations a USING(transcript_index)\n",
    "), joined AS NOT MATERIALIZED (\n",
    "  SELECT a.event_index, a.transcript_index, a.consequence_mask,\n",
    "    e.reference, e.alternate, e.position,\n",
    "    t.transcript_start::BIGINT AS tx_start, t.transcript_end::BIGINT AS tx_end,\n",
    "    t.cds_start::BIGINT AS tx_cds_start, t.cds_end::BIGINT AS tx_cds_end,\n",
    "    t.strand, t.exons, t.transcript_flags, t.peptide_edits,\n",
    "    t.cds_sequence, t.post_cds_sequence,\n",
    "    __duckvep_projection_code(t.codon_table) AS genetic_code,\n",
    "    duckvep_allele_geometry(e.position, e.reference, e.alternate) AS geometry\n",
    "  FROM annotations a JOIN events e USING (event_index)\n",
    "  LEFT JOIN selected_transcripts t USING (transcript_index)\n",
    "  CROSS JOIN validation WHERE validation.valid\n",
    "), features AS (\n",
    "  SELECT *, geometry.feature_start0::BIGINT + 1 AS vf_start,\n",
    "    geometry.feature_end0::BIGINT AS vf_end,\n",
    "    upper(CASE WHEN length(reference) = length(alternate) THEN reference\n",
    "      ELSE substring(reference, geometry.reference_difference_offset + 1,\n",
    "        geometry.reference_difference_length) END) AS feature_reference,\n",
    "    upper(CASE WHEN length(reference) = length(alternate) THEN alternate\n",
    "      ELSE substring(alternate, geometry.alternate_difference_offset + 1,\n",
    "        geometry.alternate_difference_length) END) AS feature_alternate,\n",
    "    (list_transform(list_filter((exons), lambda e: (CASE WHEN strand > 0 THEN tx_cds_start ELSE tx_cds_end END) BETWEEN e.exon_start AND e.exon_end),\n",
    "    lambda e: e.exon_cdna_start::BIGINT + CASE WHEN (strand) > 0\n",
    "      THEN (CASE WHEN strand > 0 THEN tx_cds_start ELSE tx_cds_end END)::BIGINT - e.exon_start::BIGINT\n",
    "      ELSE e.exon_end::BIGINT - (CASE WHEN strand > 0 THEN tx_cds_start ELSE tx_cds_end END)::BIGINT END)[1]) AS coding_cdna_start,\n",
    "    (list_transform(list_filter((exons), lambda e: (CASE WHEN strand > 0 THEN tx_cds_end ELSE tx_cds_start END) BETWEEN e.exon_start AND e.exon_end),\n",
    "    lambda e: e.exon_cdna_start::BIGINT + CASE WHEN (strand) > 0\n",
    "      THEN (CASE WHEN strand > 0 THEN tx_cds_end ELSE tx_cds_start END)::BIGINT - e.exon_start::BIGINT\n",
    "      ELSE e.exon_end::BIGINT - (CASE WHEN strand > 0 THEN tx_cds_end ELSE tx_cds_start END)::BIGINT END)[1]) AS coding_cdna_end,\n",
    "    greatest(exons[1].phase::BIGINT, 0) AS phase_offset\n",
    "  FROM joined\n",
    "), mapped AS (\n",
    "  SELECT *, vf_end >= tx_start AND vf_start <= tx_end AS within_transcript,\n",
    "    (list_transform(list_filter((exons), lambda e: (CASE WHEN strand > 0 THEN vf_start ELSE vf_end END) BETWEEN e.exon_start AND e.exon_end),\n",
    "    lambda e: e.exon_cdna_start::BIGINT + CASE WHEN (strand) > 0\n",
    "      THEN (CASE WHEN strand > 0 THEN vf_start ELSE vf_end END)::BIGINT - e.exon_start::BIGINT\n",
    "      ELSE e.exon_end::BIGINT - (CASE WHEN strand > 0 THEN vf_start ELSE vf_end END)::BIGINT END)[1]) AS first_cdna,\n",
    "    (list_transform(list_filter((exons), lambda e: (CASE WHEN strand > 0 THEN vf_end ELSE vf_start END) BETWEEN e.exon_start AND e.exon_end),\n",
    "    lambda e: e.exon_cdna_start::BIGINT + CASE WHEN (strand) > 0\n",
    "      THEN (CASE WHEN strand > 0 THEN vf_end ELSE vf_start END)::BIGINT - e.exon_start::BIGINT\n",
    "      ELSE e.exon_end::BIGINT - (CASE WHEN strand > 0 THEN vf_end ELSE vf_start END)::BIGINT END)[1]) AS last_cdna,\n",
    "    list_filter(range(1, length(exons)+1), lambda i:\n",
    "      vf_start <= exons[i].exon_end AND vf_end >= exons[i].exon_start) AS exon_hits,\n",
    "    list_filter(range(1, length(exons)), lambda i:\n",
    "      vf_start <= greatest(exons[i].exon_start, exons[i+1].exon_start)::BIGINT - 1 AND\n",
    "      vf_end >= least(exons[i].exon_end, exons[i+1].exon_end)::BIGINT + 1) AS intron_hits,\n",
    "    CASE WHEN strand > 0 THEN feature_alternate ELSE _duckvep_revcomp(feature_alternate) END\n",
    "      AS transcript_alternate\n",
    "  FROM features\n",
    "), cdna AS (\n",
    "  SELECT *, CASE WHEN within_transcript THEN CASE WHEN vf_start > vf_end\n",
    "      THEN coalesce(first_cdna, last_cdna + 1) ELSE first_cdna END END AS raw_cdna_start,\n",
    "    CASE WHEN within_transcript THEN CASE WHEN vf_start > vf_end\n",
    "      THEN coalesce(last_cdna, first_cdna - 1) ELSE last_cdna END END AS raw_cdna_end\n",
    "  FROM mapped\n",
    "), coding AS (\n",
    "  SELECT *, CASE WHEN raw_cdna_start BETWEEN coding_cdna_start AND coding_cdna_end\n",
    "      AND NOT (vf_start > vf_end AND (raw_cdna_start > coding_cdna_end OR raw_cdna_end < coding_cdna_start))\n",
    "      THEN raw_cdna_start - coding_cdna_start + phase_offset + 1 END AS raw_cds_start,\n",
    "    CASE WHEN raw_cdna_end BETWEEN coding_cdna_start AND coding_cdna_end\n",
    "      AND NOT (vf_start > vf_end AND (raw_cdna_start > coding_cdna_end OR raw_cdna_end < coding_cdna_start))\n",
    "      THEN raw_cdna_end - coding_cdna_start + phase_offset + 1 END AS raw_cds_end\n",
    "  FROM cdna\n",
    "), protein AS (\n",
    "  SELECT *, (raw_cds_start + 2) // 3 AS raw_protein_start,\n",
    "    (raw_cds_end + 2) // 3 AS raw_protein_end,\n",
    "    least(length(cds_sequence), raw_cds_start - 1) AS prefix_length,\n",
    "    greatest(length(cds_sequence) - raw_cds_end, 0) AS suffix_length,\n",
    "    prefix_length + length(transcript_alternate) + suffix_length AS alternate_length,\n",
    "    raw_protein_start * 3 - 3 AS codon_start0,\n",
    "    greatest((raw_protein_end - raw_protein_start + 1) * 3 + length(feature_alternate)\n",
    "      - (raw_cds_end - raw_cds_start + 1), 0) AS alternate_codon_length\n",
    "  FROM coding\n",
    "), codons AS (\n",
    "  SELECT *, CASE WHEN raw_cds_start IS NOT NULL AND raw_cds_end IS NOT NULL\n",
    "    THEN substring(cds_sequence, raw_protein_start * 3 - 2,\n",
    "      greatest((raw_protein_end - raw_protein_start + 1) * 3, 0)) END AS ref_codons,\n",
    "    CASE WHEN raw_cds_start IS NOT NULL AND raw_cds_end IS NOT NULL\n",
    "      AND cds_sequence IS NOT NULL THEN\n",
    "      CASE WHEN alternate_length >= 3 THEN\n",
    "        (substring((cds_sequence), (1) + greatest((codon_start0) - (0), 0),\n",
    "    greatest(least((codon_start0) + (alternate_codon_length), (0) + (prefix_length)) -\n",
    "      greatest((codon_start0), (0)), 0))) ||\n",
    "        (substring((transcript_alternate), (1) + greatest((codon_start0) - (prefix_length), 0),\n",
    "    greatest(least((codon_start0) + (alternate_codon_length), (prefix_length) + (length(transcript_alternate))) -\n",
    "      greatest((codon_start0), (prefix_length)), 0))) ||\n",
    "        (substring((cds_sequence), (raw_cds_end + 1) + greatest((codon_start0) - (prefix_length + length(transcript_alternate)), 0),\n",
    "    greatest(least((codon_start0) + (alternate_codon_length), (prefix_length + length(transcript_alternate)) + (suffix_length)) -\n",
    "      greatest((codon_start0), (prefix_length + length(transcript_alternate))), 0)))\n",
    "      ELSE '' END ||\n",
    "      (substring((coalesce(post_cds_sequence, '')), (1) + greatest((codon_start0) - (CASE WHEN alternate_length >= 3\n",
    "          THEN alternate_length ELSE 0 END), 0),\n",
    "    greatest(least((codon_start0) + (alternate_codon_length), (CASE WHEN alternate_length >= 3\n",
    "          THEN alternate_length ELSE 0 END) + (length(coalesce(post_cds_sequence, '')))) -\n",
    "      greatest((codon_start0), (CASE WHEN alternate_length >= 3\n",
    "          THEN alternate_length ELSE 0 END)), 0)))\n",
    "    END AS alt_codons,\n",
    "    (raw_cds_start - 1) % 3 AS changed_offset\n",
    "  FROM protein\n",
    "), translated_raw AS (\n",
    "  SELECT *, CASE WHEN regexp_full_match(feature_reference, '[ACGT]*')\n",
    "      THEN ((CASE WHEN ((ref_codons)) IS NULL THEN NULL ELSE\n",
    "    coalesce(nullif((coalesce(array_to_string(\n",
    "    list_transform(range(length((ref_codons)) // 3), lambda i: coalesce(CASE WHEN\n",
    "      (CASE WHEN regexp_full_match((substring(upper((ref_codons)), 3*i+1, 3)), '[ACGT]{3}') THEN\n",
    "    substring(((genetic_code)), (strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[1])-1)*16 +\n",
    "      (strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[2])-1)*4 + strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[3]), 1)\n",
    "  ELSE list_reduce(list_transform(list_filter(range(64), lambda j:\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[1] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[1] = 'TCAG'[j // 16 + 1]) AND\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[2] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[2] = 'TCAG'[(j // 4) % 4 + 1]) AND\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[3] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[3] = 'TCAG'[j % 4 + 1])),\n",
    "    lambda j: substring(((genetic_code)), j+1, 1)),\n",
    "    lambda consensus, aa: CASE WHEN consensus = '' THEN aa\n",
    "      WHEN consensus = aa THEN consensus ELSE 'X' END, '') END) = ''\n",
    "      THEN NULL ELSE (CASE WHEN regexp_full_match((substring(upper((ref_codons)), 3*i+1, 3)), '[ACGT]{3}') THEN\n",
    "    substring(((genetic_code)), (strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[1])-1)*16 +\n",
    "      (strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[2])-1)*4 + strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[3]), 1)\n",
    "  ELSE list_reduce(list_transform(list_filter(range(64), lambda j:\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[1] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[1] = 'TCAG'[j // 16 + 1]) AND\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[2] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[2] = 'TCAG'[(j // 4) % 4 + 1]) AND\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[3] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[3] = 'TCAG'[j % 4 + 1])),\n",
    "    lambda j: substring(((genetic_code)), j+1, 1)),\n",
    "    lambda consensus, aa: CASE WHEN consensus = '' THEN aa\n",
    "      WHEN consensus = aa THEN consensus ELSE 'X' END, '') END) END, 'X')), ''), '')) || CASE WHEN length(((ref_codons))) % 3 != 0 AND (coalesce(array_to_string(\n",
    "    list_transform(range(length((ref_codons)) // 3), lambda i: coalesce(CASE WHEN\n",
    "      (CASE WHEN regexp_full_match((substring(upper((ref_codons)), 3*i+1, 3)), '[ACGT]{3}') THEN\n",
    "    substring(((genetic_code)), (strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[1])-1)*16 +\n",
    "      (strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[2])-1)*4 + strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[3]), 1)\n",
    "  ELSE list_reduce(list_transform(list_filter(range(64), lambda j:\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[1] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[1] = 'TCAG'[j // 16 + 1]) AND\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[2] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[2] = 'TCAG'[(j // 4) % 4 + 1]) AND\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[3] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[3] = 'TCAG'[j % 4 + 1])),\n",
    "    lambda j: substring(((genetic_code)), j+1, 1)),\n",
    "    lambda consensus, aa: CASE WHEN consensus = '' THEN aa\n",
    "      WHEN consensus = aa THEN consensus ELSE 'X' END, '') END) = ''\n",
    "      THEN NULL ELSE (CASE WHEN regexp_full_match((substring(upper((ref_codons)), 3*i+1, 3)), '[ACGT]{3}') THEN\n",
    "    substring(((genetic_code)), (strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[1])-1)*16 +\n",
    "      (strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[2])-1)*4 + strpos('TCAG', (substring(upper((ref_codons)), 3*i+1, 3))[3]), 1)\n",
    "  ELSE list_reduce(list_transform(list_filter(range(64), lambda j:\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[1] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[1] = 'TCAG'[j // 16 + 1]) AND\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[2] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[2] = 'TCAG'[(j // 4) % 4 + 1]) AND\n",
    "    ((substring(upper((ref_codons)), 3*i+1, 3))[3] = 'N' OR (substring(upper((ref_codons)), 3*i+1, 3))[3] = 'TCAG'[j % 4 + 1])),\n",
    "    lambda j: substring(((genetic_code)), j+1, 1)),\n",
    "    lambda consensus, aa: CASE WHEN consensus = '' THEN aa\n",
    "      WHEN consensus = aa THEN consensus ELSE 'X' END, '') END) END, 'X')), ''), '')) != '*'\n",
    "      THEN 'X' ELSE '' END, ''), '-') END)) END AS ref_peptide,\n",
    "    CASE WHEN regexp_full_match(feature_alternate, '[ACGT]*')\n",
    "      THEN ((CASE WHEN ((alt_codons)) IS NULL THEN NULL ELSE\n",
    "    coalesce(nullif((coalesce(array_to_string(\n",
    "    list_transform(range(length((alt_codons)) // 3), lambda i: coalesce(CASE WHEN\n",
    "      (CASE WHEN regexp_full_match((substring(upper((alt_codons)), 3*i+1, 3)), '[ACGT]{3}') THEN\n",
    "    substring(((genetic_code)), (strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[1])-1)*16 +\n",
    "      (strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[2])-1)*4 + strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[3]), 1)\n",
    "  ELSE list_reduce(list_transform(list_filter(range(64), lambda j:\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[1] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[1] = 'TCAG'[j // 16 + 1]) AND\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[2] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[2] = 'TCAG'[(j // 4) % 4 + 1]) AND\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[3] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[3] = 'TCAG'[j % 4 + 1])),\n",
    "    lambda j: substring(((genetic_code)), j+1, 1)),\n",
    "    lambda consensus, aa: CASE WHEN consensus = '' THEN aa\n",
    "      WHEN consensus = aa THEN consensus ELSE 'X' END, '') END) = ''\n",
    "      THEN NULL ELSE (CASE WHEN regexp_full_match((substring(upper((alt_codons)), 3*i+1, 3)), '[ACGT]{3}') THEN\n",
    "    substring(((genetic_code)), (strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[1])-1)*16 +\n",
    "      (strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[2])-1)*4 + strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[3]), 1)\n",
    "  ELSE list_reduce(list_transform(list_filter(range(64), lambda j:\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[1] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[1] = 'TCAG'[j // 16 + 1]) AND\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[2] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[2] = 'TCAG'[(j // 4) % 4 + 1]) AND\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[3] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[3] = 'TCAG'[j % 4 + 1])),\n",
    "    lambda j: substring(((genetic_code)), j+1, 1)),\n",
    "    lambda consensus, aa: CASE WHEN consensus = '' THEN aa\n",
    "      WHEN consensus = aa THEN consensus ELSE 'X' END, '') END) END, 'X')), ''), '')) || CASE WHEN length(((alt_codons))) % 3 != 0 AND (coalesce(array_to_string(\n",
    "    list_transform(range(length((alt_codons)) // 3), lambda i: coalesce(CASE WHEN\n",
    "      (CASE WHEN regexp_full_match((substring(upper((alt_codons)), 3*i+1, 3)), '[ACGT]{3}') THEN\n",
    "    substring(((genetic_code)), (strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[1])-1)*16 +\n",
    "      (strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[2])-1)*4 + strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[3]), 1)\n",
    "  ELSE list_reduce(list_transform(list_filter(range(64), lambda j:\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[1] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[1] = 'TCAG'[j // 16 + 1]) AND\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[2] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[2] = 'TCAG'[(j // 4) % 4 + 1]) AND\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[3] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[3] = 'TCAG'[j % 4 + 1])),\n",
    "    lambda j: substring(((genetic_code)), j+1, 1)),\n",
    "    lambda consensus, aa: CASE WHEN consensus = '' THEN aa\n",
    "      WHEN consensus = aa THEN consensus ELSE 'X' END, '') END) = ''\n",
    "      THEN NULL ELSE (CASE WHEN regexp_full_match((substring(upper((alt_codons)), 3*i+1, 3)), '[ACGT]{3}') THEN\n",
    "    substring(((genetic_code)), (strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[1])-1)*16 +\n",
    "      (strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[2])-1)*4 + strpos('TCAG', (substring(upper((alt_codons)), 3*i+1, 3))[3]), 1)\n",
    "  ELSE list_reduce(list_transform(list_filter(range(64), lambda j:\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[1] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[1] = 'TCAG'[j // 16 + 1]) AND\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[2] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[2] = 'TCAG'[(j // 4) % 4 + 1]) AND\n",
    "    ((substring(upper((alt_codons)), 3*i+1, 3))[3] = 'N' OR (substring(upper((alt_codons)), 3*i+1, 3))[3] = 'TCAG'[j % 4 + 1])),\n",
    "    lambda j: substring(((genetic_code)), j+1, 1)),\n",
    "    lambda consensus, aa: CASE WHEN consensus = '' THEN aa\n",
    "      WHEN consensus = aa THEN consensus ELSE 'X' END, '') END) END, 'X')), ''), '')) != '*'\n",
    "      THEN 'X' ELSE '' END, ''), '-') END)) END AS alt_peptide\n",
    "  FROM codons\n",
    "), translated AS (\n",
    "  SELECT * EXCLUDE(ref_peptide), CASE WHEN ref_peptide IS NULL OR ref_peptide = '-'\n",
    "      THEN ref_peptide ELSE array_to_string(list_transform(range(length(ref_peptide)), lambda i:\n",
    "        coalesce(list_transform(list_filter(peptide_edits, lambda edit:\n",
    "          edit.protein_position = least(raw_protein_start, raw_protein_end) + i),\n",
    "          lambda edit: edit.alternate_amino_acid)[1], substring(ref_peptide, i+1, 1))), '')\n",
    "    END AS ref_peptide\n",
    "  FROM translated_raw\n",
    ")\n",
    "SELECT event_index, transcript_index,\n",
    "  coalesce(nullif(feature_alternate, ''), '-') AS output_allele,\n",
    "  geometry.interbase AS interbase,\n",
    "  CASE WHEN raw_cdna_start > raw_cdna_end THEN raw_cdna_end ELSE raw_cdna_start END AS cdna_start,\n",
    "  CASE WHEN raw_cdna_start > raw_cdna_end THEN raw_cdna_start ELSE raw_cdna_end END AS cdna_end,\n",
    "  CASE WHEN raw_cds_start > raw_cds_end THEN raw_cds_end ELSE raw_cds_start END AS cds_start,\n",
    "  CASE WHEN raw_cds_start > raw_cds_end THEN raw_cds_start ELSE raw_cds_end END AS cds_end,\n",
    "  CASE WHEN raw_protein_start > raw_protein_end THEN raw_protein_end ELSE raw_protein_start END AS protein_start,\n",
    "  CASE WHEN raw_protein_start > raw_protein_end THEN raw_protein_start ELSE raw_protein_end END AS protein_end,\n",
    "  exon_hits[1]::UINTEGER AS exon_first, exon_hits[-1]::UINTEGER AS exon_last,\n",
    "  length(exons)::UINTEGER AS exon_total,\n",
    "  intron_hits[1]::UINTEGER AS intron_first, intron_hits[-1]::UINTEGER AS intron_last,\n",
    "  CASE WHEN transcript_index IS NOT NULL THEN greatest(length(exons) - 1, 0)::UINTEGER END AS intron_total,\n",
    "  CASE WHEN (consequence_mask & (SELECT bit_or(consequence_mask) FROM duckvep_so_terms()\n",
    "    WHERE consequence IN ('upstream_gene_variant', 'downstream_gene_variant'))) != 0\n",
    "    THEN least(abs(vf_start - tx_start), abs(vf_start - tx_end),\n",
    "      abs(vf_end - tx_start), abs(vf_end - tx_end)) END AS transcript_distance,\n",
    "  (transcript_flags & 16) != 0 AS cds_start_nf,\n",
    "  (transcript_flags & 32) != 0 AS cds_end_nf,\n",
    "  CASE WHEN alt_peptide IS NOT NULL THEN ref_peptide END AS reference_amino_acids,\n",
    "  CASE WHEN ref_peptide IS NOT NULL THEN alt_peptide END AS alternate_amino_acids,\n",
    "  CASE WHEN ref_codons = '' THEN '-' ELSE\n",
    "    lower(substring(ref_codons, 1, changed_offset)) ||\n",
    "    substring(ref_codons, changed_offset + 1, length(feature_reference)) ||\n",
    "    lower(substring(ref_codons, changed_offset + length(feature_reference) + 1)) END\n",
    "    AS reference_codons,\n",
    "  CASE WHEN alt_codons = '' THEN '-' ELSE\n",
    "    lower(substring(alt_codons, 1, changed_offset)) ||\n",
    "    substring(alt_codons, changed_offset + 1, length(feature_alternate)) ||\n",
    "    lower(substring(alt_codons, changed_offset + length(feature_alternate) + 1)) END\n",
    "    AS alternate_codons\n",
    "FROM translated",
};
