/* The public annotation relation, emitted in the caller connection. */
static const char *const duckvep_annotate_parts[] = {
    "WITH parameters AS MATERIALIZED (SELECT CAST(__DUCKVEP_MODEL__ AS VARCHAR) AS model_name, ",
    "CAST(__DUCKVEP_UPSTREAM__ AS UBIGINT) AS upstream_distance, ",
    "CAST(__DUCKVEP_DOWNSTREAM__ AS UBIGINT) AS downstream_distance), ",
    "source AS (SELECT CAST(e.event_index AS UBIGINT) AS __duckvep_event_index, ",
    "CAST(e.seq_region AS UINTEGER) AS __duckvep_seq_region, ",
    "CAST(e.position AS UBIGINT) AS __duckvep_position, ",
    "CAST(e.reference AS VARCHAR) AS __duckvep_reference, ",
    "CAST(e.alternate AS VARCHAR) AS __duckvep_alternate, ",
    "CAST(e.end_position AS UBIGINT) AS __duckvep_end_position, ",
    "upper(CAST(e.structural_type AS VARCHAR)) AS __duckvep_explicit_structural_type, ",
    "upper(CAST(e.copy_change AS VARCHAR)) AS __duckvep_explicit_copy_change, ",
    "CAST(e.mate_seq_region AS UINTEGER) AS __duckvep_mate_seq_region, ",
    "CAST(e.mate_position AS UBIGINT) AS __duckvep_mate_position ",
    "FROM __DUCKVEP_EVENTS__ e), ",
    "typed_base AS NOT MATERIALIZED (SELECT *, ",
    "CASE WHEN starts_with(__duckvep_alternate, '<') THEN CASE __duckvep_alternate ",
    "WHEN '<DEL>' THEN 'DEL' WHEN '<DUP>' THEN 'DUP' ",
    "WHEN '<TDUP>' THEN 'TDUP' WHEN '<STR>' THEN 'STR' ",
    "WHEN '<INV>' THEN 'INV' WHEN '<INS>' THEN 'INS' ",
    "WHEN '<CNV>' THEN 'CNV' WHEN '<UNKNOWN>' THEN 'UNKNOWN' ",
    "ELSE NULL END END AS __duckvep_symbolic_structural_type, ",
    "__duckvep_alternate = '<*>' AS __duckvep_unspecified_alt, ",
    "__duckvep_alternate IN ('<NON_REF>', '*', '.') ",
    "AS __duckvep_non_variant FROM source), ",
    "typed AS NOT MATERIALIZED (SELECT *, ",
    "coalesce(__duckvep_explicit_structural_type, ",
    "__duckvep_symbolic_structural_type) AS __duckvep_structural_type ",
    "FROM typed_base), ",
    "classified AS MATERIALIZED (SELECT *, CAST(CASE ",
    "WHEN __duckvep_non_variant THEN 3 ",
    "WHEN __duckvep_unspecified_alt THEN 0 ",
    "WHEN __duckvep_mate_seq_region IS NOT NULL OR __duckvep_mate_position IS NOT NULL ",
    "THEN 2 WHEN __duckvep_explicit_structural_type IS NOT NULL ",
    "OR __duckvep_explicit_copy_change IS NOT NULL ",
    "OR (__duckvep_alternate IS NOT NULL AND ",
    "(starts_with(__duckvep_alternate, '<') OR contains(__duckvep_alternate, '[') ",
    "OR contains(__duckvep_alternate, ']'))) ",
    "OR (__duckvep_end_position IS NOT NULL AND ",
    "(__duckvep_reference IS NULL OR __duckvep_alternate IS NULL)) ",
    "THEN 1 ",
    "ELSE 0 END AS UTINYINT) AS __duckvep_kind_code, ",
    "coalesce(__duckvep_explicit_copy_change, CASE WHEN __duckvep_structural_type IS NULL ",
    "THEN 'UNKNOWN' ELSE CASE __duckvep_structural_type ",
    "WHEN 'DEL' THEN 'LOSS' WHEN 'DUP' THEN 'GAIN' WHEN 'TDUP' THEN 'GAIN' ",
    "ELSE 'UNKNOWN' END END) AS __duckvep_copy_change FROM typed), ",
    "validation AS MATERIALIZED (SELECT CASE ",
    "WHEN (SELECT model_name IS NULL OR model_name = '' FROM parameters) ",
    "THEN error('duckvep_annotate: model_name must be non-empty') ",
    "WHEN v.first_bad = 1 ",
    "THEN error('duckvep_annotate: event_index is required') ",
    "WHEN v.first_bad = 2 ",
    "THEN error('duckvep_annotate: seq_region and positive one-based position are required') ",
    "WHEN v.first_bad = 3 ",
    "THEN error('duckvep_annotate: a non-variant gVCF allele cannot carry structural or breakend fields') ",
    "WHEN v.first_bad = 4 ",
    "THEN error('duckvep_annotate: <*> cannot carry structural or breakend fields') ",
    "WHEN v.first_bad = 5 ",
    "THEN error('duckvep_annotate: a breakend requires both mate_seq_region and mate_position') ",
    "WHEN v.first_bad = 6 ",
    "THEN error('duckvep_annotate: breakend mate coordinates cannot be mixed with single-locus structural fields') ",
    "WHEN v.first_bad = 7 ",
    "THEN error('duckvep_annotate: mate_position must be positive and one-based') ",
    "WHEN v.first_bad = 8 ",
    "THEN error('duckvep_annotate: literal small variants require reference and alternate') ",
    "WHEN v.first_bad = 9 ",
    "THEN error('duckvep_annotate: symbolic alternate and structural_type disagree') ",
    "WHEN v.first_bad = 10 ",
    "THEN error('duckvep_annotate: a structural event requires end_position and a supported structural_type') ",
    "WHEN v.first_bad = 11 ",
    "THEN error('duckvep_annotate: unsupported structural_type') ",
    "ELSE true END AS valid FROM (SELECT min(bad) AS first_bad FROM (SELECT ",
    "CASE WHEN __duckvep_kind_code = 0 AND NOT __duckvep_unspecified_alt ",
    "AND __duckvep_event_index IS NOT NULL AND __duckvep_seq_region IS NOT NULL ",
    "AND __duckvep_position IS NOT NULL AND __duckvep_position <> 0 ",
    "AND __duckvep_reference IS NOT NULL AND __duckvep_reference <> '' ",
    "AND __duckvep_alternate IS NOT NULL AND __duckvep_alternate <> '' ",
    "AND __duckvep_end_position IS NULL AND __duckvep_explicit_structural_type IS NULL ",
    "AND __duckvep_explicit_copy_change IS NULL AND __duckvep_mate_seq_region IS NULL ",
    "AND __duckvep_mate_position IS NULL THEN NULL ELSE CASE ",
    "WHEN __duckvep_event_index IS NULL THEN 1 ",
    "WHEN __duckvep_seq_region IS NULL OR __duckvep_position IS NULL ",
    "OR __duckvep_position = 0 THEN 2 ",
    "WHEN __duckvep_kind_code = 3 AND (__duckvep_explicit_structural_type IS NOT NULL ",
    "OR __duckvep_explicit_copy_change IS NOT NULL ",
    "OR __duckvep_mate_seq_region IS NOT NULL ",
    "OR __duckvep_mate_position IS NOT NULL) THEN 3 ",
    "WHEN __duckvep_unspecified_alt AND (__duckvep_explicit_structural_type IS NOT NULL ",
    "OR __duckvep_explicit_copy_change IS NOT NULL ",
    "OR __duckvep_mate_seq_region IS NOT NULL ",
    "OR __duckvep_mate_position IS NOT NULL) THEN 4 ",
    "WHEN (__duckvep_mate_seq_region IS NULL) != (__duckvep_mate_position IS NULL) THEN 5 ",
    "WHEN __duckvep_kind_code = 2 AND (__duckvep_end_position IS NOT NULL ",
    "OR __duckvep_explicit_structural_type IS NOT NULL ",
    "OR __duckvep_explicit_copy_change IS NOT NULL) THEN 6 ",
    "WHEN __duckvep_kind_code = 2 AND __duckvep_mate_position = 0 THEN 7 ",
    "WHEN __duckvep_kind_code = 0 AND (__duckvep_reference IS NULL OR __duckvep_reference = '' ",
    "OR __duckvep_alternate IS NULL OR __duckvep_alternate = '') THEN 8 ",
    "WHEN __duckvep_explicit_structural_type IS NOT NULL ",
    "AND __duckvep_symbolic_structural_type IS NOT NULL ",
    "AND __duckvep_explicit_structural_type <> __duckvep_symbolic_structural_type THEN 9 ",
    "WHEN __duckvep_kind_code = 1 ",
    "AND (__duckvep_structural_type IS NULL OR __duckvep_end_position IS NULL) THEN 10 ",
    "WHEN __duckvep_kind_code = 1 ",
    "AND __duckvep_structural_type NOT IN ('DEL','DUP','TDUP','STR','INV','INS','CNV','UNKNOWN') THEN 11 ",
    "END END AS bad FROM classified) rows) v), ",
    "validated AS NOT MATERIALIZED (SELECT classified.* FROM classified CROSS JOIN validation ",
    "WHERE validation.valid), ",
    "small_events AS NOT MATERIALIZED (SELECT * FROM validated ",
    "WHERE __duckvep_kind_code = 0), ",
    "structural_events AS NOT MATERIALIZED (SELECT * FROM validated ",
    "WHERE __duckvep_kind_code = 1), ",
    "breakend_events AS NOT MATERIALIZED (SELECT * FROM validated ",
    "WHERE __duckvep_kind_code = 2), ",
    "small_compact_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_small_compact(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_reference, __duckvep_alternate, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM small_events e CROSS JOIN parameters p ",
    "WHERE (NOT coalesce(CAST(__DUCKVEP_HGVS__ AS BOOLEAN), false) OR __duckvep_unspecified_alt) ",
    "AND NOT coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false)), ",
    "small_hgvs_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_small_hgvs(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_reference, __duckvep_alternate, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM small_events e CROSS JOIN parameters p ",
    "WHERE coalesce(CAST(__DUCKVEP_HGVS__ AS BOOLEAN), false) AND NOT __duckvep_unspecified_alt ",
    "AND NOT coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false)), ",
    "small_rich_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_small_rich(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_reference, __duckvep_alternate, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM small_events e CROSS JOIN parameters p ",
    "WHERE (NOT coalesce(CAST(__DUCKVEP_HGVS__ AS BOOLEAN), false) OR __duckvep_unspecified_alt) ",
    "AND coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false)), ",
    "small_rich_hgvs_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_small_rich_hgvs(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_reference, __duckvep_alternate, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM small_events e CROSS JOIN parameters p ",
    "WHERE coalesce(CAST(__DUCKVEP_HGVS__ AS BOOLEAN), false) AND NOT __duckvep_unspecified_alt ",
    "AND coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false)), ",
    "structural_compact_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_structural_compact(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_end_position, __duckvep_structural_type, ",
    "__duckvep_copy_change, p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM structural_events e CROSS JOIN parameters p WHERE NOT coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false)), ",
    "structural_rich_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_structural_rich(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_end_position, __duckvep_structural_type, ",
    "__duckvep_copy_change, p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM structural_events e CROSS JOIN parameters p WHERE coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false)), ",
    "breakend_compact_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_breakend_compact(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_mate_seq_region, __duckvep_mate_position, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM breakend_events e CROSS JOIN parameters p WHERE NOT coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false)), ",
    "breakend_rich_raw AS (SELECT e.*, ",
    "unnest(_duckvep_annotate_breakend_rich(p.model_name, __duckvep_seq_region, ",
    "__duckvep_position, __duckvep_mate_seq_region, __duckvep_mate_position, ",
    "p.upstream_distance, p.downstream_distance)) AS annotation ",
    "FROM breakend_events e CROSS JOIN parameters p WHERE coalesce(CAST(__DUCKVEP_RICH__ AS BOOLEAN), false)), ",
    "small_compact AS (SELECT __duckvep_event_index AS event_index, ",
    "'small_variant' AS duckvep_event_kind, annotation.* ",
    "FROM small_compact_raw), ",
    "small_hgvs AS (SELECT __duckvep_event_index AS event_index, ",
    "'small_variant' AS duckvep_event_kind, annotation.* FROM small_hgvs_raw), ",
    "small_rich AS (SELECT __duckvep_event_index AS event_index, ",
    "'small_variant' AS duckvep_event_kind, ",
    "annotation.* EXCLUDE (status, reason), annotation.status AS duckvep_status, ",
    "annotation.reason AS duckvep_reason FROM small_rich_raw), ",
    "small_rich_hgvs AS (SELECT __duckvep_event_index AS event_index, ",
    "'small_variant' AS duckvep_event_kind, ",
    "annotation.* EXCLUDE (status, reason), annotation.status AS duckvep_status, ",
    "annotation.reason AS duckvep_reason ",
    "FROM small_rich_hgvs_raw), ",
    "structural_compact AS (SELECT __duckvep_event_index AS event_index, ",
    "'structural_variant' AS duckvep_event_kind, annotation.* ",
    "FROM structural_compact_raw), ",
    "structural_rich AS (SELECT __duckvep_event_index AS event_index, ",
    "'structural_variant' AS duckvep_event_kind, ",
    "annotation.* EXCLUDE (status, reason), annotation.status AS duckvep_status, ",
    "annotation.reason AS duckvep_reason ",
    "FROM structural_rich_raw), ",
    "breakend_compact AS (SELECT __duckvep_event_index AS event_index, ",
    "'breakend' AS duckvep_event_kind, annotation.* ",
    "FROM breakend_compact_raw), ",
    "breakend_rich AS (SELECT __duckvep_event_index AS event_index, ",
    "'breakend' AS duckvep_event_kind, ",
    "annotation.* EXCLUDE (status, reason), annotation.status AS duckvep_status, ",
    "annotation.reason AS duckvep_reason ",
    "FROM breakend_rich_raw) ",
    "SELECT * FROM small_compact UNION ALL BY NAME SELECT * FROM small_hgvs ",
    "UNION ALL BY NAME SELECT * FROM small_rich ",
    "UNION ALL BY NAME SELECT * FROM small_rich_hgvs ",
    "UNION ALL BY NAME SELECT * FROM structural_compact ",
    "UNION ALL BY NAME SELECT * FROM structural_rich ",
    "UNION ALL BY NAME SELECT * FROM breakend_compact ",
    "UNION ALL BY NAME SELECT * FROM breakend_rich",
};
